.data
.include "mk.data"
.include "teste1.data"
.include "teste2.data"
.include "teste3.data"
.include "teste4.data"
.include "teste5.data"
.include "teste6.data"
.include "teste7.data"
.include "teste8.data"
.include "teste9.data"
.include "c1.data"
.include "c2.data"
.include "c3.data"
.include "c4.data"